apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dying-smelt-go-gitops
  description: This is GitOps manifest for dying-smelt-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: dying-smelt-go
    janus-idp.io/tekton: dying-smelt-go 
    backstage.io/kubernetes-id: dying-smelt-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dying-smelt-go
