apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dying-smelt-go
  janus-idp.io/tekton: dying-smelt-go
  backstage.io/kubernetes-id: dying-smelt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dying-smelt-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
