apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dying-smelt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dying-smelt-go 
  name: dying-smelt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dying-smelt-go 
